cod_behavior:
  ros__parameters:
    cod_bt_path:
      "COD_Behavior/cod_bt/singlenav_tree.xml"
    nav_pose:
      home:  #补给区位置坐标
        frame_id: "map"
        position:
          x: 0.0
          y: 0.0
          z: 0.0
        orientation:
          w: 1.0

      main:  #中心增益区位置坐标1
        frame_id: "map"
        position:
          x: 5.05161
          y: -2.56074
          z: 0.0
        orientation:
          w: 1.0

      main1:  #中心增益区位置坐标2
        frame_id: "map"
        position:
          x: 5.05161
          y: 0.5
          z: 0.0
        orientation:
          w: 1.0

    D_patrol_pose:
      first:  #回防位置坐标1
        frame_id: "map"
        position:
          x: 2.0
          y: -1.0
          z: 0.0
        orientation:
          w: 1.0

      second:  #回防位置坐标2
        frame_id: "map"
        position:
          x: -2.0
          y: -1.0
          z: 0.0
        orientation:
          w: 1.0

    A_patrol_pose:
      first:  #前压位置坐标1
        frame_id: "map"
        position:
          x: 3.05161
          y: -4.0
          z: 0.0
        orientation:
          w: 1.0

      second:  #前压位置坐标2
        frame_id: "map"
        position:
          x: 1.05161
          y: -4.0
          z: 0.0
        orientation:
          w: 1.0
